"""Application configuration.

Project paths and German-market constants live here as plain module-level values; anything that may
vary by environment (API keys, the database location) is a typed :class:`Settings` field sourced from
``.env.local`` / the process environment.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# -- Project paths --------------------------------------------------------------
# src/eex_forecast/config.py -> repo root is two levels up from the package directory.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CONFIG_DIR = PROJECT_ROOT / "config"
GEO_DIR = DATA_DIR / "geo"
CANDIDATES_DIR = DATA_DIR / "candidates"
WEATHER_CACHE_DIR = DATA_DIR / "weather_cache"
RANK_DIR = DATA_DIR / "rank"
ANALYSIS_DIR = DATA_DIR / "analysis"  # correlation matrices and point maps
MODELS_DIR = DATA_DIR / "models"  # trained model artifacts (regenerated by `eex model train`)
FORECAST_DIR = DATA_DIR / "forecast"  # written forecasts (CSV) and plots
TUNING_DIR = (
    DATA_DIR / "tuning"
)  # per-model tuning reports (cutoffs + metadata) from `eex model tune`
AGGREGATION_DIR = DATA_DIR / "aggregation"  # weather-aggregation A/B reports from `eex analyze aggregation`
ABLATION_DIR = DATA_DIR / "ablation"  # feature-removal (ablation) reports from `eex analyze ablation`

# Tuned hyperparameters per model, written by `eex model tune` and read by `eex model train`.
HYPERPARAMS_PATH = CONFIG_DIR / "hyperparams.json"

# -- German market / domain constants -------------------------------------------
AREA_CODE = "DE"
ENTSOE_ZONE = "DE_LU"  # entsoe-py area key for the German-Luxembourg bidding zone
ENTSOE_ZONE_EIC = "10Y1001A1001A82H"
MARKET_TIMEZONE = "Europe/Berlin"
HORIZON_DAYS = 14
# Rolling window (days) that `eex update` re-fetches each run. ENTSO-E publishes actuals with a lag and
# revises them, so re-pulling the last couple of weeks keeps the database current without a full backfill.
DEFAULT_REFRESH_DAYS = 14

# Cross-border nuclear availability. Germany closed its own reactors in April 2023, so nuclear reaches the
# German price only through imports - chiefly from France. We sum the available nuclear capacity (installed
# minus outages) of these zones into one column; because planned outages publish years ahead, it is known
# across the forecast horizon. Extensible to BE/CZ; entsoe-py zone keys.
NUCLEAR_ZONES: tuple[str, ...] = ("FR",)
NUCLEAR_COLUMN = "nuclear_available_mw"

# Cross-border transfer capacity (NTC). The interconnectors cap how much power can flow between DE and each
# neighbour, so they set how tightly the zones couple: ample NTC pulls prices together, a reduced border
# (maintenance/outage) lets a zone decouple and spike. We fetch month-ahead forecasted NTC [11.1] per
# border in both directions - which, like nuclear outages, is published ahead and so covers the forecast
# horizon. Borders (label -> entsoe-py zone) are DE's month-ahead-publishing neighbours. Per-border columns
# ntc_imp_<b> (into DE) / ntc_exp_<b> (out of DE) are stored; the price model reads the summed totals.
NTC_BORDERS: dict[str, str] = {
    "at": "AT",
    "be": "BE",
    "cz": "CZ",
    "dk1": "DK_1",
    "dk2": "DK_2",
    "fr": "FR",
    "nl": "NL",
    "no2": "NO_2",
    "se4": "SE_4",
}
NTC_IMPORT_PREFIX = "ntc_imp_"  # capacity INTO DE from the neighbour
NTC_EXPORT_PREFIX = "ntc_exp_"  # capacity OUT of DE to the neighbour

# Continental-DE sampling box (lat_min, lat_max, lon_min, lon_max), including the North Sea and
# Baltic offshore wind regions. Used to keep candidate-point grid search tight and fast.
DE_BBOX = (47.0, 56.0, 5.5, 15.5)

# -- Neighbour wind -------------------------------------------------------------
# DE's price is coupled to its neighbours through the interconnectors: abundant wind in a neighbouring
# bidding zone depresses that zone's price and, via imports, DE's. We rank each neighbour's own wind
# candidate points against DE price and keep the two best - a cross-border wind proxy for the price model.
# The set mirrors the wind-relevant DE neighbours (offshore North Sea/Baltic + onshore) used upstream.
WIND_NEIGHBOURS: tuple[str, ...] = ("DK", "NL", "PL", "FR", "CH", "CZ", "AT")
NEIGHBOUR_POINTS_PER_COUNTRY = 2
NEIGHBOUR_MIN_DISTANCE_KM = 50.0  # keep the two chosen points per neighbour spatially distinct

# Property values that identify each country across the GISCO (ISO2/ISO3) and EEZ (name) GeoJSON schemes.
# Any feature property value equal (case-insensitively) to one of these marks the feature as that country.
COUNTRY_IDENTIFIERS: dict[str, frozenset[str]] = {
    "DE": frozenset({"DE", "DEU", "GERMANY"}),
    "DK": frozenset({"DK", "DNK", "DENMARK"}),
    "NL": frozenset({"NL", "NLD", "NETHERLANDS"}),
    "PL": frozenset({"PL", "POL", "POLAND"}),
    "FR": frozenset({"FR", "FRA", "FRANCE"}),
    "CH": frozenset({"CH", "CHE", "SWITZERLAND"}),
    "CZ": frozenset({"CZ", "CZE", "CZECHIA", "CZECH REPUBLIC"}),
    "AT": frozenset({"AT", "AUT", "AUSTRIA"}),
}

# Continental box for neighbour candidate sampling (lat_min, lat_max, lon_min, lon_max). Per-country
# geometry is clipped to each country's ring extent within this box. Bounds are deliberately tight to the
# DE-relevant wind band: lat_max 58.5 drops the Faroese North-Atlantic EEZ (tagged SOVEREIGN1=Denmark),
# lat_min 43 drops Corsica/the Mediterranean, and the longitudes drop the French Atlantic far west while
# keeping every neighbour's mainland and its North Sea / Baltic offshore.
EUROPE_BBOX = (43.0, 58.5, -5.0, 24.0)

# The chosen weather points, written by the point-search step and read by the weather backfill.
WEATHER_POINTS_PATH = CONFIG_DIR / "weather_points.json"


class Settings(BaseSettings):
    """Environment-sourced runtime settings (``.env.local`` takes precedence over ``.env``)."""

    model_config = SettingsConfigDict(
        env_file=(".env", ".env.local"),
        env_file_encoding="utf-8",
        populate_by_name=True,
        extra="ignore",
    )

    entsoe_api_key: str = Field(default="", validation_alias="ENTSO_E_API_KEY")
    openmeteo_api_key: str = Field(default="", validation_alias="OPENMETEO_API_KEY")
    db_path: Path = Field(default=DATA_DIR / "eex.db", validation_alias="DB_PATH")

    def require_entsoe_key(self) -> str:
        """Return the ENTSO-E token or raise a clear error if it is not configured."""
        if not self.entsoe_api_key:
            raise RuntimeError(
                "ENTSO_E_API_KEY is not set. Add it to .env.local (see .env.example)."
            )
        return self.entsoe_api_key


@lru_cache
def get_settings() -> Settings:
    """Return the process-wide settings singleton."""
    return Settings()
