"""Application configuration.

Project paths and German-market constants live here as plain module-level values; anything that may
vary by environment (API keys, the database location) is a typed :class:`Settings` field sourced from
``.env.local`` / the process environment.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# -- Project paths --------------------------------------------------------------
# src/eex_forecast/config.py -> repo root is two levels up from the package directory.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CONFIG_DIR = PROJECT_ROOT / "config"
LOGS_DIR = PROJECT_ROOT / "logs"  # timestamped per-run CLI logs (pruned after LOG_RETENTION_DAYS)
LOG_RETENTION_DAYS = 14  # delete run logs older than this on startup (<= 0 disables pruning)
GEO_DIR = DATA_DIR / "geo"
CANDIDATES_DIR = DATA_DIR / "candidates"
WEATHER_CACHE_DIR = DATA_DIR / "weather_cache"
RANK_DIR = DATA_DIR / "rank"
ANALYSIS_DIR = DATA_DIR / "analysis"  # correlation matrices and point maps
MODELS_DIR = DATA_DIR / "models"  # trained model artifacts (regenerated by `eex model train`)
FORECAST_DIR = DATA_DIR / "forecast"  # written forecasts (CSV) and plots
TUNING_DIR = (
    DATA_DIR / "tuning"
)  # per-model tuning reports (cutoffs + metadata) from `eex model tune`
AGGREGATION_DIR = (
    DATA_DIR / "aggregation"
)  # weather-aggregation A/B reports from `eex analyze aggregation`
ABLATION_DIR = (
    DATA_DIR / "ablation"
)  # feature-removal (ablation) reports from `eex analyze ablation`
EVALUATION_DIR = DATA_DIR / "evaluation"  # frozen-cutoff backtest reports from `eex analyze eval`

# -- Ensemble forecasting -------------------------------------------------------
# The ensemble path propagates ECMWF's 51-member weather ensemble through the already-trained
# deterministic models to produce a weather-driven spread. It never writes to the production database:
# these are separate files so an ensemble run cannot touch a measured actual, and so the (large,
# regenerable) member-weather archive can be deleted without losing the permanent per-member forecasts.
ENSEMBLE_DB_PATH = DATA_DIR / "eex_ensemble.db"  # permanent: run metadata + per-member predictions
ENSEMBLE_WEATHER_DB_PATH = DATA_DIR / "eex_ensemble_weather.db"  # prunable raw member weather
# Open-Meteo retains individual members for only ~3 days, so archiving is the sole route to an ensemble
# history. Raw weather is ~86 MB per run, hence a bounded rolling window rather than keeping everything;
# the small per-member forecast table is never pruned.
ENSEMBLE_RETENTION_RUNS = 30

# Tuned hyperparameters per model, written by `eex model tune` and read by `eex model train`.
HYPERPARAMS_PATH = CONFIG_DIR / "hyperparams.json"
BACKTEST_CUTOFFS_PATH = (
    CONFIG_DIR / "backtest_cutoffs.yaml"
)  # frozen walk-forward cutoffs (all tools)

# -- German market / domain constants -------------------------------------------
AREA_CODE = "DE"
ENTSOE_ZONE = "DE_LU"  # entsoe-py area key for the German-Luxembourg bidding zone
ENTSOE_ZONE_EIC = "10Y1001A1001A82H"
MARKET_TIMEZONE = "Europe/Berlin"
# Unknown delivery days per run, counted from the hour after the last *settled* price. That anchor jumps
# forward a day when the day-ahead auction clears around midday, while the weather fetch window stays
# anchored to today's midnight - so an evening run reaches one day further than ECMWF does, the
# incomplete final day is dropped whole, and 13 days are published instead of 14. That is expected, not
# a fault; a morning run on the same data publishes all 14.
HORIZON_DAYS = 14
# How much settled history the forecast run reads, and therefore shows. One value governs every output
# that displays history - forecast.csv and all three plots are built from the same trimmed frame - so
# changing it here moves them together. The forward-only ensemble summary is unaffected.
#
# This is presentation, not modelling: the forecast itself does not change. But it cannot be shrunk
# freely, because the read window is also what `features.price_lags` looks back into. Below about eight
# days the 168 h price lag starts resolving to NaN on the near horizon, which does change the forecast.
# The window start is snapped forward to a Europe/Berlin midnight, so the retained span is whole German
# delivery days rather than exactly this many 24 h blocks.
FORECAST_HISTORY_DAYS = 21
# Rolling window (days) that `eex update` re-fetches each run. ENTSO-E publishes actuals with a lag and
# revises them, so re-pulling the last couple of weeks keeps the database current without a full backfill.
DEFAULT_REFRESH_DAYS = 14

# Cross-border nuclear availability. Germany closed its own reactors in April 2023, so nuclear reaches the
# German price only through imports - chiefly from France. We sum the available nuclear capacity (installed
# minus outages) of these zones into one column; because planned outages publish years ahead, it is known
# across the forecast horizon. Extensible to BE/CZ; entsoe-py zone keys.
NUCLEAR_ZONES: tuple[str, ...] = ("FR",)
NUCLEAR_COLUMN = "nuclear_available_mw"

# Cross-border transfer capacity (NTC). The interconnectors cap how much power can flow between DE and each
# neighbour, so they set how tightly the zones couple: ample NTC pulls prices together, a reduced border
# (maintenance/outage) lets a zone decouple and spike. We fetch forecasted NTC [11.1] per border in both
# directions - week-ahead blended over month-ahead (near week refined, far horizon on month-ahead) - which,
# like nuclear outages, is published ahead and so covers the forecast horizon. Borders (label -> entsoe-py
# zone) are DE's NTC-publishing neighbours. Per-border columns ntc_imp_<b> (into DE) / ntc_exp_<b> (out of
# DE) are stored; the price model reads the summed totals.
NTC_BORDERS: dict[str, str] = {
    "at": "AT",
    "be": "BE",
    "cz": "CZ",
    "dk1": "DK_1",
    "dk2": "DK_2",
    "fr": "FR",
    "nl": "NL",
    "no2": "NO_2",
    "se4": "SE_4",
}
NTC_IMPORT_PREFIX = "ntc_imp_"  # capacity INTO DE from the neighbour
NTC_EXPORT_PREFIX = "ntc_exp_"  # capacity OUT of DE to the neighbour

# Continental-DE sampling box (lat_min, lat_max, lon_min, lon_max), including the North Sea and
# Baltic offshore wind regions. Used to keep candidate-point grid search tight and fast.
DE_BBOX = (47.0, 56.0, 5.5, 15.5)

# -- Neighbour wind -------------------------------------------------------------
# DE's price is coupled to its neighbours through the interconnectors: abundant wind in a neighbouring
# bidding zone depresses that zone's price and, via imports, DE's. We rank each neighbour's own wind
# candidate points against DE price and keep the two best - a cross-border wind proxy for the price model.
# The set is DE's interconnected, wind-relevant neighbours (offshore North Sea/Baltic + onshore).
WIND_NEIGHBOURS: tuple[str, ...] = ("DK", "NL", "PL", "FR", "CH", "CZ", "AT")
NEIGHBOUR_POINTS_PER_COUNTRY = 2
NEIGHBOUR_MIN_DISTANCE_KM = 50.0  # keep the two chosen points per neighbour spatially distinct

# Property values that identify each country across the GISCO (ISO2/ISO3) and EEZ (name) GeoJSON schemes.
# Any feature property value equal (case-insensitively) to one of these marks the feature as that country.
COUNTRY_IDENTIFIERS: dict[str, frozenset[str]] = {
    "DE": frozenset({"DE", "DEU", "GERMANY"}),
    "DK": frozenset({"DK", "DNK", "DENMARK"}),
    "NL": frozenset({"NL", "NLD", "NETHERLANDS"}),
    "PL": frozenset({"PL", "POL", "POLAND"}),
    "FR": frozenset({"FR", "FRA", "FRANCE"}),
    "CH": frozenset({"CH", "CHE", "SWITZERLAND"}),
    "CZ": frozenset({"CZ", "CZE", "CZECHIA", "CZECH REPUBLIC"}),
    "AT": frozenset({"AT", "AUT", "AUSTRIA"}),
}

# Continental box for neighbour candidate sampling (lat_min, lat_max, lon_min, lon_max). Per-country
# geometry is clipped to each country's ring extent within this box. Bounds are deliberately tight to the
# DE-relevant wind band: lat_max 58.5 drops the Faroese North-Atlantic EEZ (tagged SOVEREIGN1=Denmark),
# lat_min 43 drops Corsica/the Mediterranean, and the longitudes drop the French Atlantic far west while
# keeping every neighbour's mainland and its North Sea / Baltic offshore.
EUROPE_BBOX = (43.0, 58.5, -5.0, 24.0)

# The chosen weather points, written by the point-search step and read by the weather backfill.
WEATHER_POINTS_PATH = CONFIG_DIR / "weather_points.json"


class Settings(BaseSettings):
    """Environment-sourced runtime settings (``.env.local`` takes precedence over ``.env``)."""

    model_config = SettingsConfigDict(
        env_file=(".env", ".env.local"),
        env_file_encoding="utf-8",
        populate_by_name=True,
        extra="ignore",
    )

    entsoe_api_key: str = Field(default="", validation_alias="ENTSO_E_API_KEY")
    openmeteo_api_key: str = Field(default="", validation_alias="OPENMETEO_API_KEY")
    db_path: Path = Field(default=DATA_DIR / "eex.db", validation_alias="DB_PATH")

    def require_entsoe_key(self) -> str:
        """Return the ENTSO-E token or raise a clear error if it is not configured."""
        if not self.entsoe_api_key:
            raise RuntimeError(
                "ENTSO_E_API_KEY is not set. Add it to .env.local (see .env.example)."
            )
        return self.entsoe_api_key


@lru_cache
def get_settings() -> Settings:
    """Return the process-wide settings singleton."""
    return Settings()
